CREATE TABLE SAVINGSACCOUNTS (
    ACCOUNTID NUMBER PRIMARY KEY,
    CUSTOMERNAME VARCHAR2(50),
    BALANCE NUMBER
);

INSERT INTO SAVINGSACCOUNTS VALUES (
    101,
    'John',
    10000
);

INSERT INTO SAVINGSACCOUNTS VALUES (
    102,
    'Mary',
    5000
);

INSERT INTO SAVINGSACCOUNTS VALUES (
    103,
    'Ali',
    12000
);

COMMIT;

CREATE OR REPLACE PROCEDURE PROCESSMONTHLYINTEREST AS
BEGIN
    UPDATE SAVINGSACCOUNTS
    SET
        BALANCE = BALANCE + (
            BALANCE * 0.01
        );
    COMMIT;
END;
/

EXEC ProcessMonthlyInterest;