CREATE TABLE EMPLOYEES (
    EMPID NUMBER PRIMARY KEY,
    EMPNAME VARCHAR2(20),
    DEPARTMENT VARCHAR2(20),
    SALARY NUMBER
);

INSERT INTO EMPLOYEES VALUES (
    1,
    'Asha',
    'HR',
    30000
);

INSERT INTO EMPLOYEES VALUES (
    2,
    'Ravi',
    'IT',
    40000
);

INSERT INTO EMPLOYEES VALUES (
    3,
    'Sneha',
    'IT',
    45000
);

INSERT INTO EMPLOYEES VALUES (
    4,
    'Karan',
    'Finance',
    38000
);

COMMIT;

CREATE OR REPLACE PROCEDURE UPDATEEMPLOYEEBONUS (
    P_DEPARTMENT IN VARCHAR2,
    P_BONUS_PERCENT IN NUMBER
) AS
BEGIN
    UPDATE EMPLOYEES
    SET
        SALARY = SALARY + (
            SALARY * P_BONUS_PERCENT / 100
        )
    WHERE
        DEPARTMENT = P_DEPARTMENT;
    COMMIT;
END;
/